#include "p16f887.inc"

; CONFIG1
; __config 0x3FF9
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

 CBLOCK 0x70
 DECENA
 UNIDAD
 GRADOS
 CELSIUS
 WA
 STATUSA
 DISPLAY
 CONT1
 DISPLAY
 ENDC
 
    ORG 0x00
    GOTO INICIO
    ORG 0x04
    GOTO IRS

 INICIO
          BANKSEL TRISA
	  CLRF TRISD        ;PUERTO D COMO SALIDA
	  CLRF TRISC       ; PUERTO C COMO SALIDA
	  MOVLW B'00000001'   
	  MOVWF TRISB ; RB0 COMO ENTRADA
	  MOVWF	TRISA ; RA0 COMO ENTRADA
	  
	  BANKSEL ANSEL ;RA0 COMO ENTRADA ANALÓGICA
	  MOVLW 0x01	;EL RESTO DE LAS E/S COMO DIGITALES
	  MOVWF ANSEL 
	  CLRF ANSELH
	  
	  BANKSEL PORTA
	  CLRF PORTD 
	  CLRF PORTC       ;LIMPIO LOS PUERTOS
	  CLRF PORTB
	  CLRF PORTA
	  
	  BANKSEL OPTION_REG
	  MOVLW B'10000111'
	  MOVWF OPTION_REG       ;PS=256
	  
	  BANKSEL INTCON
	  MOVLW B'00110000'
	  MOVWF INTCON   ;ACTIVO INTERRUPCIONES POR TMR0 Y RB0
	  
	  BANKSEL TMR0
	  MOVLW .236      ;PRECARGO EL TMR0
	  MOVWF TMR0     ;PARA TENER 10mseg PARA RESFRECAR LOS DISPLAYS
	  
	  MOVLW 0x3F
	  MOVWF UNIDAD       ; UNIDAD
	  MOVLW 0x3F
	  MOVWF DECENA     ;DECENA
	  MOVLW 0x63		    
	  MOVWF GRADOS
	  MOVLW 0x39
	  MOVWF CELSIUS
	  MOVLW .4
	  MOVWF DISPLAY    ;CONTADOR PARA SABER EN QUE DISPLAY ESTOY
	  BANKSEL INTCON
	  BSF	  INTCON,GIE
	  
	  GOTO $
	  
IRS	  ;SALVAR CONTEXTO
	  MOVWF WA
	  SWAPF STATUS,W
	  MOVWF STATUSA   
	  ;VER BANDERAS
	  BTFSC INTCON,INTF    
	  GOTO RB0SR
	  BTFSC INTCON,T0IF   
	  GOTO TMR0SR
	  BTFSC PIR1,TMR1IF
	  GOTO TMR1SR
	  BTFSC PIR1,ADIF
	  GOTO ADSR
	  GOTO SALIR
	  
RB0SR	  BCF INTCON,INTF
	  BSF ADCON0,GO
	  GOTO SALIR

ADSR	  BCF PIR1,ADIF
	  ;MODIFICAR DECENA Y UNIDAD
			
TMR0SR	  BCF INTCON,T0IF
	  MOVLW	    .236
	  MOVWF	    TMR0
	  DECFSZ    DISPLAY,F
	  GOTO	    MOSTRAR	  
	  GOTO	    MOVDECENA	
	      
	  ;MOSTRAR DISPLAYS
MOSTRAR	 
	  BCF	    STATUS,Z
	  MOVF	    DISPLAY,W	    
	  SUBLW	    .3
	  MOVWF	    DISPLAY
	  BTFSC	    STATUS,Z
	  GOTO	    MOVLETRA
	  BTFSC	    DISPLAY,0
	  GOTO	    MOVGRADO
	  BTFSC	    DISPLAY,1
	  GOTO	    MOVUNIDAD
	  
	  
MOVLETRA  MOVF	CELSIUS,W
	  MOVWF	PORTD
	  CLRF	PORTC
	  BSF	PORTC,3
	  GOTO	SALIR
MOVGRADO  MOVF	GRADOS,W
	  MOVWF	PORTD
	  CLRF	PORTC
	  BSF	PORTC,2	 
	  GOTO	SALIR
MOVUNIDAD MOVF	UNIDAD,W
	  MOVWF	PORTD
	  CLRF	PORTC
	  BSF	PORTC,1	 
	  GOTO	SALIR
MOVDECENA MOVF	DECENA,W
	  MOVWF	PORTD
	  CLRF	PORTC
	  BSF	PORTC,0
	  MOVLW .4
	  MOVWF	DISPLAY
	  GOTO	SALIR	
	  
TMR1SR	  BCF PIR1,TMR1IF
	  MOVLW	0x0B
	  MOVWF	TMR1H
	  MOVLW	0xDC
	  MOVWF	TMR1L
	  DECFSZ CONT1
	  GOTO SALIR
	  ;SI ES 0 MANDAR EL DATO 
	  ;Y MOSTRAR LEDs
	  
SALIR	  ;RECUPERAR CONTEXTO
	  SWAPF	STATUSA,W
	  MOVWF	STATUS
	  SWAPF	WA,F
	  SWAPF	WA,W
	  RETFIE	  

TABLA     ADDWF PCL,F
	  RETLW 0X3F       ;0
          RETLW 0x06       ;1
	  RETLW 0x5B       ;2
	  RETLW 0x4F       ;3
	  RETLW 0x66       ;4
	  RETLW 0x6D       ;5
	  RETLW 0x7D       ;6
	  RETLW 0x07       ;7
	  RETLW 0x7F       ;8
	  RETLW 0x6F       ;9

	  END
 
